# Generated by Django 5.0.6 on 2024-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_users_city_remove_users_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
